#!/bin/sh

#updating sitemap
./update-sitemap
git commit -m "updated sitemap" dist/sitemap.txt
git push

#building and minifying
rm -rf build.web
./qmlcore/build -m

#updating gh-pages
git checkout gh-pages
git pull
cp -r build.web/* .

#adding all sitemap urls
FILES=$(tail --lines='+2' < dist/sitemap.txt | sed -r "s/^https:\/\/pureqml.com\///" | xargs)
mkdir lessons 2> /dev/null
for FILE in $FILES; do
	cp index.html $FILE
done

git add $FILES

git commit -a -m "updated site"

#restoring master
git checkout master
git push --all #a bit dangerous lol
